version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    volumes:
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/dashboards:/var/lib/grafana/dashboards
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_PASSWORD: codesmith
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
  alert_manager:
    

    ports:
    - '3000:3000'
    depends_on:
    - prometheus
    - prometheus2
    - prometheus3
  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_data:/prometheus
    ports:
    - '9090:9090'
  prometheus2:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus2.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_data:/prometheus2
    ports:
    - '9091:9090'
  prometheus3:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus3.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_data:/prometheus3
    ports:
    - '9092:9090'
volumes:
  prometheus_data: null
  grafana_data: null
