version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD : codesmith
      GF_PATHS_DATA : /var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - ./node_exporter:/etc/node_exporter
    ports:
      - 9100:9100
    networks:
      - monitoring

networks:
  monitoring:
    external: true

volumes:
  prometheus_data:
  grafana_data:
