global:
  scrape_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
- /etc/prometheus/rules/*.yml
scrape_configs:
- job_name: Demo6
  static_configs:
  - targets:
    - 6.7.8.9:6789
