global:
  scrape_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
- /etc/prometheus/rules/*.yaml
scrape_configs:
- job_name: Demo2
  static_configs:
  - targets:
    - 10.0.10.137:1234
