global:
  scrape_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
- /etc/prometheus/rules/*.yml
scrape_configs:
- job_name: Demo1
  static_configs:
  - targets:
    - 1.2.3.4:1234
