global:
  scrape_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
- /etc/prometheus/rules/*.yml
scrape_configs:
- job_name: Demo2
  static_configs:
  - targets:
    - 2.3.4.5:2345
