global:
  scrape_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
- /etc/prometheus/rules/*.yml
scrape_configs:
- job_name: Demo9
  static_configs:
  - targets:
    - 9.0.1.2:9012
    - 9.0.1.2:0123
    - 9.0.1.2:1234
