global:
  scrape_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
- /etc/prometheus/rules/*.yml
scrape_configs:
- job_name: Demo7
  static_configs:
  - targets:
    - 7.8.9.0:7890
