apiVersion: 1
datasources:
- name: prometheus1
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus1:9090
  basicAuth: false
  isDefault: false
  editable: true
- name: prometheus3
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus3:9090
  basicAuth: false
  isDefault: false
  editable: true
- name: prometheus4
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus4:9090
  basicAuth: false
  isDefault: false
  editable: true
- name: prometheus6
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus6:9090
  basicAuth: false
  isDefault: false
  editable: true
- name: prometheus7
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus7:9090
  basicAuth: false
  isDefault: false
  editable: true
- name: prometheus9
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus9:9090
  basicAuth: false
  isDefault: false
  editable: true
- name: prometheus10
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus10:9090
  basicAuth: false
  isDefault: false
  editable: true
- name: prometheus11
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus11:9090
  basicAuth: false
  isDefault: false
  editable: true
