apiVersion: 1
datasources:
  - name: prometheus1
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: prometheus2
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9091
    basicAuth: false
    isDefault: false
    editable: true
  - name: prometheus3
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9092
    basicAuth: false
    isDefault: false
    editable: true
